# Generated by Django 3.2.9 on 2021-11-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=256)),
                ('category', models.CharField(max_length=32)),
                ('units', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField()),
                ('prerequisites', models.ManyToManyField(blank=True, default=None, to='course.Courses')),
            ],
        ),
    ]
