# Generated by Django 3.2.9 on 2021-11-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.TextField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
