# Generated by Django 3.2.9 on 2021-11-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_courses_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.TextField(max_length=256),
        ),
    ]
