# Generated by Django 3.2.9 on 2021-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_slug'),
        ('course', '0005_remove_courses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='categories',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
